/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import turnibook.Operaciones;


/**
 *
 * @author wrtfix
 */
public class Usuarios extends javax.swing.JFrame {

    /**
     * Creates new form Usuarios
     */
    public Usuarios() {
        initComponents();
        tablaProfesional.addMouseListener(new MouseAdapter() {
            @Override
              public void mouseClicked(MouseEvent e) 
              {
                 int fila = tablaProfesional.rowAtPoint(e.getPoint());
                 int columna = tablaProfesional.columnAtPoint(e.getPoint());
                 if ((fila > -1) && (columna > -1)){
                     botonEliminar.setEnabled(true);
                 }
                     
              }
        });
        agregarProfesionales();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel2 = new javax.swing.JLabel();
        nombreProfesional = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        contraProfesional = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProfesional = new javax.swing.JTable();
        botonAgregar = new javax.swing.JToggleButton();
        botonEliminar = new javax.swing.JToggleButton();
        botonGuardar = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        intervalo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        checkLunes = new javax.swing.JCheckBox();
        checkMartes = new javax.swing.JCheckBox();
        checkMiercoles = new javax.swing.JCheckBox();
        checkJueves = new javax.swing.JCheckBox();
        lunesDesde = new javax.swing.JTextField();
        lunesHasta = new javax.swing.JTextField();
        martesHasta = new javax.swing.JTextField();
        martesDesde = new javax.swing.JTextField();
        miercolesHasta = new javax.swing.JTextField();
        miercolesDesde = new javax.swing.JTextField();
        juevesHasta = new javax.swing.JTextField();
        juevesDesde = new javax.swing.JTextField();
        checkViernes = new javax.swing.JCheckBox();
        viernesDesde = new javax.swing.JTextField();
        viernesHasta = new javax.swing.JTextField();
        checkSabado = new javax.swing.JCheckBox();
        sabadoDesde = new javax.swing.JTextField();
        sabadoHasta = new javax.swing.JTextField();
        checkDomingo = new javax.swing.JCheckBox();
        domingoDesde = new javax.swing.JTextField();
        domingoHasta = new javax.swing.JTextField();
        checkDescanso = new javax.swing.JCheckBox();
        descanso = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configuracion de Usuario");

        jLabel2.setText("Nombre");

        jLabel3.setText("Contraseña");

        jLabel7.setText("Nombre");

        tablaProfesional.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero de Profesional", "Nombre", "Password"
            }
        ));
        tablaProfesional.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tablaProfesionalInputMethodTextChanged(evt);
            }
        });
        tablaProfesional.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablaProfesionalKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablaProfesional);

        botonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/turnibook/images/ico_agregar.gif"))); // NOI18N
        botonAgregar.setText("Agregar");
        botonAgregar.setMaximumSize(new java.awt.Dimension(93, 29));
        botonAgregar.setMinimumSize(new java.awt.Dimension(93, 29));
        botonAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAgregarMouseClicked(evt);
            }
        });
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        botonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/turnibook/images/eliminar.gif"))); // NOI18N
        botonEliminar.setText("Eliminar");
        botonEliminar.setEnabled(false);
        botonEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonEliminarMouseClicked(evt);
            }
        });

        botonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/turnibook/images/icoGuardar.gif"))); // NOI18N
        botonGuardar.setText("Guardar");
        botonGuardar.setEnabled(false);
        botonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonGuardarMouseClicked(evt);
            }
        });

        jButton1.setText("Regresar");

        jButton2.setText("Generar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Intervalors de turno");

        jLabel4.setText("Dias Laborales:");

        checkLunes.setText("Lunes");
        checkLunes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkLunesActionPerformed(evt);
            }
        });

        checkMartes.setText("Martes");
        checkMartes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMartesActionPerformed(evt);
            }
        });

        checkMiercoles.setText("Miercoles");
        checkMiercoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMiercolesActionPerformed(evt);
            }
        });

        checkJueves.setText("Jueves");
        checkJueves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkJuevesActionPerformed(evt);
            }
        });

        lunesDesde.setEditable(false);
        lunesDesde.setText("Desde");

        lunesHasta.setEditable(false);
        lunesHasta.setText("Hasta");
        lunesHasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lunesHastaActionPerformed(evt);
            }
        });

        martesHasta.setEditable(false);
        martesHasta.setText("Hasta");

        martesDesde.setEditable(false);
        martesDesde.setText("Desde");

        miercolesHasta.setEditable(false);
        miercolesHasta.setText("Hasta");

        miercolesDesde.setEditable(false);
        miercolesDesde.setText("Desde");

        juevesHasta.setEditable(false);
        juevesHasta.setText("Hasta");

        juevesDesde.setEditable(false);
        juevesDesde.setText("Desde");

        checkViernes.setText("Viernes");
        checkViernes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkViernesActionPerformed(evt);
            }
        });

        viernesDesde.setEditable(false);
        viernesDesde.setText("Desde");

        viernesHasta.setEditable(false);
        viernesHasta.setText("Hasta");

        checkSabado.setText("Sabado");
        checkSabado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSabadoActionPerformed(evt);
            }
        });

        sabadoDesde.setEditable(false);
        sabadoDesde.setText("Desde");

        sabadoHasta.setEditable(false);
        sabadoHasta.setText("Hasta");

        checkDomingo.setText("Domingo");
        checkDomingo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkDomingoActionPerformed(evt);
            }
        });

        domingoDesde.setEditable(false);
        domingoDesde.setText("Desde");

        domingoHasta.setEditable(false);
        domingoHasta.setText("Hasta");

        checkDescanso.setText("Descansos");
        checkDescanso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkDescansoActionPerformed(evt);
            }
        });

        descanso.setEditable(false);
        descanso.setText("0");

        jLabel5.setText("Horario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreProfesional)
                            .addComponent(contraProfesional)))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkDomingo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(checkLunes, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(checkSabado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(checkViernes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(checkJueves, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(checkMiercoles, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(checkMartes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lunesDesde)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lunesHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(martesDesde)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(martesHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(miercolesDesde)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(miercolesHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(sabadoDesde)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sabadoHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(domingoDesde)
                                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(domingoHasta)
                                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(juevesDesde, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(viernesDesde))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(viernesHasta)
                                    .addComponent(juevesHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(158, 158, 158))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonGuardar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(checkDescanso)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descanso, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(intervalo, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(4, 4, 4))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreProfesional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(13, 13, 13)
                        .addComponent(jLabel3))
                    .addComponent(contraProfesional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEliminar)
                    .addComponent(botonGuardar))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intervalo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkDescanso)
                    .addComponent(descanso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkLunes)
                    .addComponent(lunesDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lunesHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkMartes)
                    .addComponent(martesDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(martesHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkMiercoles)
                    .addComponent(miercolesDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(miercolesHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkJueves)
                    .addComponent(juevesDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(juevesHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkViernes)
                    .addComponent(viernesDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viernesHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkSabado)
                    .addComponent(sabadoDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sabadoHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkDomingo)
                    .addComponent(domingoDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(domingoHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Este metodo consulta una tabla
    public void agregarProfesionales(){
        // Creo una instacia de operaciones
        Operaciones o = new Operaciones();
        // Guardo en un clase del tipo resultado de consulta la consulta que hice sobre operaciones
        ResultSet resultado = o.consultar("select * from profesional");
        try {
            DefaultTableModel model = (DefaultTableModel) tablaProfesional.getModel();
            while(resultado.next()){
                //Obtengo los elementos de resultado.getString(numero de columna)
                model.addRow(new Object[]{resultado.getString(1),resultado.getString(3), resultado.getString(4)});
            }
        } catch (SQLException ex) {
            Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    private void botonAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAgregarMouseClicked
    }//GEN-LAST:event_botonAgregarMouseClicked

    private void botonEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEliminarMouseClicked
        int row = tablaProfesional.getSelectedRow();
        if (row>=0){
             DefaultTableModel model = (DefaultTableModel) tablaProfesional.getModel();
             model.removeRow(row);
        }else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar algun profesional");
        }
            
    }//GEN-LAST:event_botonEliminarMouseClicked

    private void botonGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarMouseClicked
        //Agregar logica de guardar en la base de datos
        botonGuardar.setEnabled(false);
        tablaProfesional.clearSelection();
    }//GEN-LAST:event_botonGuardarMouseClicked

    private void tablaProfesionalInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tablaProfesionalInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaProfesionalInputMethodTextChanged

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        if(!nombreProfesional.getText().isEmpty() && !contraProfesional.getText().isEmpty()){
            DefaultTableModel model = (DefaultTableModel) tablaProfesional.getModel();
            //Cargar los profesionales existentes
            model.addRow(new Object[]{model.getRowCount()+1,nombreProfesional.getText(), contraProfesional.getText()});
            
            
        }else
        {
            JOptionPane.showMessageDialog(null, "Debe ingresar nombre de profesional y password");
        }
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void tablaProfesionalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaProfesionalKeyPressed
        botonGuardar.setEnabled(true);
    }//GEN-LAST:event_tablaProfesionalKeyPressed
    
    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
            Operaciones o = new Operaciones();
            o.insertar("insert into horario(lunes_desde, lunes_hasta,martes_desde,martes_hasta,miercoles_desde,miercoles_hasta,jueves_desde, jueves_hasta, viernes_desde, viernes_hasta, sabado_desde, sabado_hasta, domingo_desde, domingo_hasta, intervalo, descansos ) values('" + lunesDesde.getText() + "','" + lunesHasta.getText() + "','" + martesDesde.getText() + "','" + martesHasta.getText() + "','" + miercolesDesde.getText() + "','" + miercolesHasta.getText() + "','" + juevesDesde.getText() + "','" + juevesHasta.getText() + "','" + viernesDesde.getText() + "','" + viernesHasta.getText() + "','" + sabadoDesde.getText() + "','" + sabadoHasta.getText() + "','" + domingoDesde.getText() + "','" + domingoHasta.getText() + "'," + intervalo.getText() + ","+descanso.getText()+")");
            
            o.insertar("insert into profesional(id_horario,nombre,clave) values ("+o.IdHorario() +",'"+nombreProfesional.getText()+"','"+contraProfesional.getText()+"')");
            JOptionPane.showMessageDialog(null, "Se genero el horario ");
      
    }//GEN-LAST:event_jButton2MouseClicked

    private void lunesHastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lunesHastaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lunesHastaActionPerformed

    private void checkLunesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkLunesActionPerformed
       if(checkLunes.isSelected()){
            lunesDesde.setEditable(true);
            lunesHasta.setEditable(true);
            lunesDesde.setText("");
            lunesHasta.setText("");
        }
        else{
            lunesDesde.setEditable(false);
            lunesHasta.setEditable(false);
        }
    }//GEN-LAST:event_checkLunesActionPerformed

    private void checkMartesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMartesActionPerformed
         if(checkMartes.isSelected()){
            martesDesde.setEditable(true);
            martesHasta.setEditable(true);
            martesDesde.setText("");
            martesHasta.setText("");
        }
        else{
            martesDesde.setEditable(false);
            martesHasta.setEditable(false);
        }
    }//GEN-LAST:event_checkMartesActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void checkMiercolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMiercolesActionPerformed
         if(checkMiercoles.isSelected()){
            miercolesDesde.setEditable(true);
            miercolesHasta.setEditable(true);
            miercolesDesde.setText("");
            miercolesHasta.setText("");
        }
        else{
            miercolesDesde.setEditable(false);
            miercolesHasta.setEditable(false);
        }
    }//GEN-LAST:event_checkMiercolesActionPerformed

    private void checkJuevesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkJuevesActionPerformed
        if(checkJueves.isSelected()){
            juevesDesde.setEditable(true);
            juevesHasta.setEditable(true);
        }
        else{
            juevesDesde.setEditable(false);
            juevesHasta.setEditable(false);
        }
    }//GEN-LAST:event_checkJuevesActionPerformed

    private void checkViernesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkViernesActionPerformed
        if(checkViernes.isSelected()){
            viernesDesde.setEditable(true);
            viernesHasta.setEditable(true);
            viernesDesde.setText("");
            viernesHasta.setText("");
            
        }
        else{
            viernesDesde.setEditable(false);
            viernesHasta.setEditable(false);
        }
    }//GEN-LAST:event_checkViernesActionPerformed

    private void checkSabadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSabadoActionPerformed
                if(checkSabado.isSelected()){
            sabadoDesde.setEditable(true);
            sabadoHasta.setEditable(true);
            sabadoDesde.setText("");
            sabadoHasta.setText("");
            
        }
        else{
            sabadoDesde.setEditable(false);
            sabadoHasta.setEditable(false);
        }
    }//GEN-LAST:event_checkSabadoActionPerformed

    private void checkDomingoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkDomingoActionPerformed
            if(checkDomingo.isSelected()){
            domingoDesde.setEditable(true);
            domingoHasta.setEditable(true);
            domingoDesde.setText("");
            domingoHasta.setText("");
        }
        else{
            domingoDesde.setEditable(false);
            domingoHasta.setEditable(false);
        }
    }//GEN-LAST:event_checkDomingoActionPerformed

    private void checkDescansoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkDescansoActionPerformed
         if(checkDescanso.isSelected()){
            descanso.setEditable(true);
            descanso.setText("");
         }
        else
        descanso.setEditable(false);
    }//GEN-LAST:event_checkDescansoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuarios().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botonAgregar;
    private javax.swing.JToggleButton botonEliminar;
    private javax.swing.JToggleButton botonGuardar;
    private javax.swing.JCheckBox checkDescanso;
    private javax.swing.JCheckBox checkDomingo;
    private javax.swing.JCheckBox checkJueves;
    private javax.swing.JCheckBox checkLunes;
    private javax.swing.JCheckBox checkMartes;
    private javax.swing.JCheckBox checkMiercoles;
    private javax.swing.JCheckBox checkSabado;
    private javax.swing.JCheckBox checkViernes;
    private javax.swing.JPasswordField contraProfesional;
    private javax.swing.JTextField descanso;
    private javax.swing.JTextField domingoDesde;
    private javax.swing.JTextField domingoHasta;
    private javax.swing.JTextField intervalo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField juevesDesde;
    private javax.swing.JTextField juevesHasta;
    private javax.swing.JTextField lunesDesde;
    private javax.swing.JTextField lunesHasta;
    private javax.swing.JTextField martesDesde;
    private javax.swing.JTextField martesHasta;
    private javax.swing.JTextField miercolesDesde;
    private javax.swing.JTextField miercolesHasta;
    private javax.swing.JTextField nombreProfesional;
    private javax.swing.JTextField sabadoDesde;
    private javax.swing.JTextField sabadoHasta;
    private javax.swing.JTable tablaProfesional;
    private javax.swing.JTextField viernesDesde;
    private javax.swing.JTextField viernesHasta;
    // End of variables declaration//GEN-END:variables
}
